name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies and build Tailwind CSS
        run: |
          npm install
          npm run build-css
          
      - name: Generate secure configuration
        run: |
          mkdir -p js
          cat > js/config.js << 'EOF'
          // Configurazione generata automaticamente
          (function() {
            // Configurazione di fallback per sviluppo
            const defaultConfig = {
              token: '',
              user: 'CalcioDM3',
              repo: 'CalcioDM3',
              playersFolder: 'GIOCATORI',
              ratingsFolder: 'VALUTAZIONI',
              usersFolder: 'UTENTI',
              adminUsers: ['Gianmarco Saponaro', 'Marco D\\'Amato']
            };

            // Cerca il token nei secrets di GitHub Pages
            const urlParams = new URLSearchParams(window.location.search);
            const tokenFromUrl = urlParams.get('token');
            
            // Configurazione finale
            const finalConfig = {
              ...defaultConfig,
              token: tokenFromUrl || '${{ secrets.ACCESS_TOKEN }}' || defaultConfig.token
            };

            // Imposta la configurazione globale
            window.GITHUB_CONFIG = finalConfig;

            console.log('Configurazione GitHub caricata:', {
              ...finalConfig,
              token: finalConfig.token ? '***' : 'MISSING'
            });
          })();
          EOF
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
