name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Build with environment variables
        run: |
          # Crea un file di configurazione con il token
          echo "const GITHUB_TOKEN = '${{ secrets.ACCESS_TOKEN }}';" > js/config.js
          echo "const GITHUB_USER = 'CalcioDM3';" >> js/config.js
          echo "const GITHUB_REPO = 'CalcioDM3';" >> js/config.js
          # Aggiungi altre variabili se necessario
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
